# package|display name|private webview directories
com.sankuai.meituan|美团|app_webview_mt_webview files/cips/common/mtplatform/assets/mtwebview
com.jingdong.app.mall|京东|app_tbs app_tbs_64 app_tbs_common_share app_webview_d6 app_x5webview
com.taobao.taobao|淘宝|app_u4_webview app_u4sdk
com.taobao.idlefish|闲鱼|app_u4_webview app_u4sdk
com.tencent.mobileqq|QQ|app_x5webview app_tbs app_tbs_64 app_tbs_common_share app_xwalk_-1 app_xwalkconfig app_xwalkplugin app_xweb_data
com.alipay.mobile.quinox|支付宝国际 Play 版|app_h5container app_plugins_lib app_myweb_anr app_webview_mywebview_0
com.dingtalk.mobile|钉钉|app_h5apps app_h5container app_u4_webview app_u4sdk

